package db.hibernate.tables.isearch;

// Generated 2015-10-26 17:52:10 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClickLog generated by hbm2java
 */
@Entity
@Table(name = "click_log", catalog = "isearch")
public class ClickLog implements java.io.Serializable {

	private Integer id;
	private User user;
	private Category category;
	private String query;
	private String url;
	private String classification;
	private Integer value;
	private Date date;
	private String title;
	private String abstr;
	private Integer rank;
	private Integer clickRank;

	public ClickLog() {
	}

	public ClickLog(User user, Category category, String query, String url,
			String classification, Integer value, Date date, String title,
			String abstr, Integer rank, Integer clickRank) {
		this.user = user;
		this.category = category;
		this.query = query;
		this.url = url;
		this.classification = classification;
		this.value = value;
		this.date = date;
		this.title = title;
		this.abstr = abstr;
		this.rank = rank;
		this.clickRank = clickRank;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "query")
	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "classification")
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "abstr")
	public String getAbstr() {
		return this.abstr;
	}

	public void setAbstr(String abstr) {
		this.abstr = abstr;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "click_rank")
	public Integer getClickRank() {
		return this.clickRank;
	}

	public void setClickRank(Integer clickRank) {
		this.clickRank = clickRank;
	}

}
