package db.hibernate.tables.isearch;

// Generated 2015-10-26 17:52:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GroupInfo generated by hbm2java
 */
@Entity
@Table(name = "group_info", catalog = "isearch")
public class GroupInfo implements java.io.Serializable {

	private Integer id;
	private String remark;
	private Set<UserGroups> userGroupses = new HashSet<UserGroups>(0);
	private Set<GroupToCategory> groupToCategories = new HashSet<GroupToCategory>(
			0);

	public GroupInfo() {
	}

	public GroupInfo(String remark, Set<UserGroups> userGroupses,
			Set<GroupToCategory> groupToCategories) {
		this.remark = remark;
		this.userGroupses = userGroupses;
		this.groupToCategories = groupToCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "remark", length = 45)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupInfo")
	public Set<UserGroups> getUserGroupses() {
		return this.userGroupses;
	}

	public void setUserGroupses(Set<UserGroups> userGroupses) {
		this.userGroupses = userGroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupInfo")
	public Set<GroupToCategory> getGroupToCategories() {
		return this.groupToCategories;
	}

	public void setGroupToCategories(Set<GroupToCategory> groupToCategories) {
		this.groupToCategories = groupToCategories;
	}

}
