package db.hibernate.tables.isearch;

// Generated 2015-10-26 17:52:10 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HotWords generated by hbm2java
 */
@Entity
@Table(name = "hot_words", catalog = "isearch")
public class HotWords implements java.io.Serializable {

	private Integer hid;
	private String hotwords;
	private Date date;

	public HotWords() {
	}

	public HotWords(String hotwords, Date date) {
		this.hotwords = hotwords;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hid", unique = true, nullable = false)
	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	@Column(name = "hotwords", nullable = false)
	public String getHotwords() {
		return this.hotwords;
	}

	public void setHotwords(String hotwords) {
		this.hotwords = hotwords;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
