package db.hibernate.tables.isearch;

// Generated 2015-10-26 17:52:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QfgFeatures generated by hbm2java
 */
@Entity
@Table(name = "qfg_features", catalog = "isearch")
public class QfgFeatures implements java.io.Serializable {

	private Integer id;
	private Queries queriesByQueryFirst;
	private Queries queriesByQuerySecond;
	private String cookie;
	private Double edlevGt2;
	private Double charPov;
	private Double charSuf;
	private Double wordPov;
	private Double wordSuf;
	private Double commonWords;
	private Double wordJDistance;

	public QfgFeatures() {
	}

	public QfgFeatures(Queries queriesByQueryFirst,
			Queries queriesByQuerySecond, String cookie, Double edlevGt2,
			Double charPov, Double charSuf, Double wordPov, Double wordSuf,
			Double commonWords, Double wordJDistance) {
		this.queriesByQueryFirst = queriesByQueryFirst;
		this.queriesByQuerySecond = queriesByQuerySecond;
		this.cookie = cookie;
		this.edlevGt2 = edlevGt2;
		this.charPov = charPov;
		this.charSuf = charSuf;
		this.wordPov = wordPov;
		this.wordSuf = wordSuf;
		this.commonWords = commonWords;
		this.wordJDistance = wordJDistance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "query_first")
	public Queries getQueriesByQueryFirst() {
		return this.queriesByQueryFirst;
	}

	public void setQueriesByQueryFirst(Queries queriesByQueryFirst) {
		this.queriesByQueryFirst = queriesByQueryFirst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "query_second")
	public Queries getQueriesByQuerySecond() {
		return this.queriesByQuerySecond;
	}

	public void setQueriesByQuerySecond(Queries queriesByQuerySecond) {
		this.queriesByQuerySecond = queriesByQuerySecond;
	}

	@Column(name = "cookie", length = 45)
	public String getCookie() {
		return this.cookie;
	}

	public void setCookie(String cookie) {
		this.cookie = cookie;
	}

	@Column(name = "edlevGT2", precision = 11)
	public Double getEdlevGt2() {
		return this.edlevGt2;
	}

	public void setEdlevGt2(Double edlevGt2) {
		this.edlevGt2 = edlevGt2;
	}

	@Column(name = "char_pov", precision = 11)
	public Double getCharPov() {
		return this.charPov;
	}

	public void setCharPov(Double charPov) {
		this.charPov = charPov;
	}

	@Column(name = "char_suf", precision = 11)
	public Double getCharSuf() {
		return this.charSuf;
	}

	public void setCharSuf(Double charSuf) {
		this.charSuf = charSuf;
	}

	@Column(name = "word_pov", precision = 11)
	public Double getWordPov() {
		return this.wordPov;
	}

	public void setWordPov(Double wordPov) {
		this.wordPov = wordPov;
	}

	@Column(name = "word_suf", precision = 11)
	public Double getWordSuf() {
		return this.wordSuf;
	}

	public void setWordSuf(Double wordSuf) {
		this.wordSuf = wordSuf;
	}

	@Column(name = "common_words", precision = 11)
	public Double getCommonWords() {
		return this.commonWords;
	}

	public void setCommonWords(Double commonWords) {
		this.commonWords = commonWords;
	}

	@Column(name = "word_j_distance", precision = 11)
	public Double getWordJDistance() {
		return this.wordJDistance;
	}

	public void setWordJDistance(Double wordJDistance) {
		this.wordJDistance = wordJDistance;
	}

}
