package db.hibernate.tables.isearch;

// Generated 2015-10-26 17:52:10 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserFavorWords generated by hbm2java
 */
@Entity
@Table(name = "user_favor_words", catalog = "isearch")
public class UserFavorWords implements java.io.Serializable {

	private Integer wordid;
	private User user;
	private Category category;
	private String word;
	private String classification;
	private String relevance;
	private Date date;
	private double value;

	public UserFavorWords() {
	}

	public UserFavorWords(User user, String word, String classification,
			Date date, double value) {
		this.user = user;
		this.word = word;
		this.classification = classification;
		this.date = date;
		this.value = value;
	}

	public UserFavorWords(User user, Category category, String word,
			String classification, String relevance, Date date, double value) {
		this.user = user;
		this.category = category;
		this.word = word;
		this.classification = classification;
		this.relevance = relevance;
		this.date = date;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "wordid", unique = true, nullable = false)
	public Integer getWordid() {
		return this.wordid;
	}

	public void setWordid(Integer wordid) {
		this.wordid = wordid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "word", nullable = false)
	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	@Column(name = "classification", nullable = false)
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "relevance")
	public String getRelevance() {
		return this.relevance;
	}

	public void setRelevance(String relevance) {
		this.relevance = relevance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "value", nullable = false, precision = 22, scale = 0)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
