package db.hibernate.tables.isearch;

// Generated 2015-10-26 17:52:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "isearch")
public class User implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String password;
	private String emailadress;
	private String imei;
	private String cookieid;
	private Set<UserFavorWords> userFavorWordses = new HashSet<UserFavorWords>(
			0);
	private Set<UserSeSetting> userSeSettings = new HashSet<UserSeSetting>(0);
	private Set<UserInterestValue> userInterestValues = new HashSet<UserInterestValue>(
			0);
	private Set<UserGroups> userGroupses = new HashSet<UserGroups>(0);
	private Set<ClickLog> clickLogs = new HashSet<ClickLog>(0);

	public User() {
	}

	public User(String username, String password, String emailadress,
			String imei, String cookieid, Set<UserFavorWords> userFavorWordses,
			Set<UserSeSetting> userSeSettings,
			Set<UserInterestValue> userInterestValues,
			Set<UserGroups> userGroupses, Set<ClickLog> clickLogs) {
		this.username = username;
		this.password = password;
		this.emailadress = emailadress;
		this.imei = imei;
		this.cookieid = cookieid;
		this.userFavorWordses = userFavorWordses;
		this.userSeSettings = userSeSettings;
		this.userInterestValues = userInterestValues;
		this.userGroupses = userGroupses;
		this.clickLogs = clickLogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userid", unique = true, nullable = false)
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "emailadress")
	public String getEmailadress() {
		return this.emailadress;
	}

	public void setEmailadress(String emailadress) {
		this.emailadress = emailadress;
	}

	@Column(name = "imei")
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Column(name = "cookieid")
	public String getCookieid() {
		return this.cookieid;
	}

	public void setCookieid(String cookieid) {
		this.cookieid = cookieid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserFavorWords> getUserFavorWordses() {
		return this.userFavorWordses;
	}

	public void setUserFavorWordses(Set<UserFavorWords> userFavorWordses) {
		this.userFavorWordses = userFavorWordses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserSeSetting> getUserSeSettings() {
		return this.userSeSettings;
	}

	public void setUserSeSettings(Set<UserSeSetting> userSeSettings) {
		this.userSeSettings = userSeSettings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserInterestValue> getUserInterestValues() {
		return this.userInterestValues;
	}

	public void setUserInterestValues(Set<UserInterestValue> userInterestValues) {
		this.userInterestValues = userInterestValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserGroups> getUserGroupses() {
		return this.userGroupses;
	}

	public void setUserGroupses(Set<UserGroups> userGroupses) {
		this.userGroupses = userGroupses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ClickLog> getClickLogs() {
		return this.clickLogs;
	}

	public void setClickLogs(Set<ClickLog> clickLogs) {
		this.clickLogs = clickLogs;
	}

}
