package db.hibernate.tables.isearch;

// Generated 2015-10-26 17:52:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserSeSetting generated by hbm2java
 */
@Entity
@Table(name = "user_se_setting", catalog = "isearch")
public class UserSeSetting implements java.io.Serializable {

	private Integer id;
	private User user;
	private String username;
	private String seSetting;

	public UserSeSetting() {
	}

	public UserSeSetting(User user, String username, String seSetting) {
		this.user = user;
		this.username = username;
		this.seSetting = seSetting;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "se_setting", nullable = false)
	public String getSeSetting() {
		return this.seSetting;
	}

	public void setSeSetting(String seSetting) {
		this.seSetting = seSetting;
	}

}
